import "./globals.css"; // Make sure to have a globals.css file

export const metadata = {
  title: "Multi-Role SaaS Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}